Feature/aditional support page
Sensational-Life/asd pull request #27
Opened 2022-02-01 19:42 UTC by andrejskalnins

I noticed that we are using react router v5.4 not the latest one v6 
Side note: I'll clean up the class names to more readable ones.

2022-02-01 21:26 UTC, youssef910 requested changes

2022-02-01 21:26 UTC, youssef910 commented on client/src/App.js
> +
check the indentation

2022-02-01 21:26 UTC, youssef910 commented on client/src/pages/AdditionalSupport/AdditionalSupport.css
> +
remove empty lines

2022-02-01 21:26 UTC, youssef910 commented on client/src/pages/AdditionalSupport/AdditionalSupport.js
> +				<div className="content-child1">
indentation again

2022-02-02 10:47 UTC, khaledkz commented on client/src/pages/AdditionalSupport/AdditionalSupport.js
> +			></img>
you should use self close tag for <img />

2022-02-02 10:48 UTC, khaledkz approved these changes
looks good, just left a minor comments also need to fix indentation

2022-02-03 17:16 UTC, youssef910 approved these changes

2022-02-03 17:18 UTC, merged