Feature/timetable user not registered
Sensational-Life/asd pull request #44
Opened 2022-02-06 15:08 UTC by andrejskalnins

2022-02-06 22:54 UTC, Abdalrazaq94 submitted a review, later dismissed
client/src/pages/Timetables/TimetableNotRegistered.js 
in this file, you need to delete the import FooterNav and Footer Icon and Footer Logo.

and in the end of the code delete 
<FooterLogo />
			<FooterNav />
			<FooterIcon />
			
			
			as we have changed already, otherwise you will have conflict

2022-02-07 10:31 UTC, khaledkz commented on client/src/pages/Timetables/TimetableNotRegistered.css
> +
can you remove empty line

2022-02-07 10:31 UTC, khaledkz commented on client/src/pages/Timetables/TimetableNotRegistered.css
> +
same here

2022-02-07 10:31 UTC, khaledkz commented on client/src/pages/Timetables/TimetableNotRegistered.css
> +
same here

2022-02-07 10:32 UTC, khaledkz commented on client/src/pages/Timetables/TimetableNotRegistered.css
> +}
remove all empty lines

2022-02-07 10:33 UTC, khaledkz commented on client/src/pages/Timetables/TimetableNotRegistered.js
> +			</main>
can you fix indentation

2022-02-07 10:34 UTC, khaledkz reviewed
looks good, try to review your PR and look to your code here after creating PR a lot of comments are the same about indentation and empty lines.

2022-02-08 21:38 UTC, youssef910 requested changes

2022-02-08 21:38 UTC, youssef910 commented on client/src/pages/Timetables/TimetableNotRegistered.js
> +							<Link to="/login">Sign Up.</Link>
add the right link to login page

2022-02-08 21:59 UTC, andrejskalnins commented on client/src/pages/Timetables/TimetableNotRegistered.js
> +							<Link to="/login">Sign Up.</Link>
Hi, is the correct path /getstarted?

2022-02-08 22:00 UTC, andrejskalnins commented on client/src/pages/Timetables/TimetableNotRegistered.js
> +							<Link to="/login">Sign Up.</Link>
Oh nwm spotted it

2022-02-09 20:24 UTC, merged