feature/section7 landing page
Sensational-Life/asd pull request #5
Opened 2022-01-21 21:47 UTC by Megan-Sen

2022-01-24 18:51 UTC, youssef910 commented on client/src/index.html
> +		<title>Section7</title>
should be changed to site title, not the task title

2022-01-24 18:53 UTC, youssef910 commented on client/src/pages/Home/WeSupportYou/WeSupportYou.js
> +import section7Image from "https://i.postimg.cc/Xvq2SPBx/supporting-elderly-woman-2021-09-24-03-07-01-utc.jpg";
link imported and never used .. delete

2022-01-24 18:57 UTC, youssef910 requested changes

2022-01-24 18:57 UTC, youssef910 commented on client/src/pages/Home/WeSupportYou/dummyWeSupportYou.html
> +<!DOCTYPE html>
why you need to add html ---- you done the same work on js file

2022-01-24 18:57 UTC, youssef910 commented on client/src/pages/Home/Footer/Footer.js
> +import React from "react";
you should do the footer in a separate branch and PR

2022-01-25 22:57 UTC, filkovsp requested changes

2022-01-25 23:10 UTC, filkovsp approved these changes

2022-01-25 23:12 UTC, filkovsp approved these changes

2022-01-25 23:12 UTC, filkovsp approved these changes
looks done now

2022-01-25 23:13 UTC, filkovsp approved these changes
done as of the latest commit

2022-01-25 23:13 UTC, filkovsp approved these changes

2022-01-25 23:13 UTC, filkovsp approved these changes
done as of the latest commit

2022-01-25 23:14 UTC, filkovsp approved these changes
done as of the latest commit

2022-01-25 23:14 UTC, filkovsp approved these changes
done as of the latest commit

2022-01-25 23:15 UTC, filkovsp approved these changes
done as of the latest commit

2022-01-25 23:15 UTC, filkovsp approved these changes
done as of the latest commit

2022-01-25 23:56 UTC, merged