section 10 faq
Sensational-Life/asd pull request #52
Opened 2022-02-07 01:22 UTC by Dilekcn

2022-02-07 07:25 UTC, ewaDev requested changes

2022-02-07 07:25 UTC, ewaDev commented on client/src/pages/FrequentlyAskedQuestions/FrequentlyAskedQuestions.css
> +.faQuestions_container {
please keep naming consistent - in the other file you use faq_container

2022-02-07 07:25 UTC, ewaDev commented on client/src/pages/Home/Faq/Faq.css
> +    background-color:var(--blue-color) ;
please fix indentation

2022-02-07 07:25 UTC, ewaDev commented on client/src/pages/Home/Faq/Faq.js
> +                to="/faq"
is this the correct indentation?

2022-02-07 10:29 UTC, khaledkz commented on client/src/pages/FrequentlyAskedQuestions/FrequentlyAskedQuestions.js
> +
can you remove this empty line

2022-02-07 13:44 UTC, Dilekcn commented on client/src/pages/Home/Faq/Faq.css
> +    background-color:var(--blue-color) ;
indentation fixed

2022-02-07 13:45 UTC, Dilekcn commented on client/src/pages/Home/Faq/Faq.js
> +                to="/faq"
indentation fixed

2022-02-07 17:55 UTC, EwaGrabowiecka approved these changes

2022-02-08 10:53 UTC, khaledkz requested changes
Can you fix the merge conflict

2022-02-08 11:04 UTC, khaledkz approved these changes

2022-02-08 11:11 UTC, ewaDev approved these changes

2022-02-08 11:11 UTC, merged